// Generated by gencpp from file brics_actuator/ProgramExecuteVelocity.msg
// DO NOT EDIT!


#ifndef BRICS_ACTUATOR_MESSAGE_PROGRAMEXECUTEVELOCITY_H
#define BRICS_ACTUATOR_MESSAGE_PROGRAMEXECUTEVELOCITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace brics_actuator
{
template <class ContainerAllocator>
struct ProgramExecuteVelocity_
{
  typedef ProgramExecuteVelocity_<ContainerAllocator> Type;

  ProgramExecuteVelocity_()
    : velocity(0)  {
    }
  ProgramExecuteVelocity_(const ContainerAllocator& _alloc)
    : velocity(0)  {
  (void)_alloc;
    }



   typedef int8_t _velocity_type;
  _velocity_type velocity;




  typedef boost::shared_ptr< ::brics_actuator::ProgramExecuteVelocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::brics_actuator::ProgramExecuteVelocity_<ContainerAllocator> const> ConstPtr;

}; // struct ProgramExecuteVelocity_

typedef ::brics_actuator::ProgramExecuteVelocity_<std::allocator<void> > ProgramExecuteVelocity;

typedef boost::shared_ptr< ::brics_actuator::ProgramExecuteVelocity > ProgramExecuteVelocityPtr;
typedef boost::shared_ptr< ::brics_actuator::ProgramExecuteVelocity const> ProgramExecuteVelocityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::brics_actuator::ProgramExecuteVelocity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::brics_actuator::ProgramExecuteVelocity_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace brics_actuator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'brics_actuator': ['/home/arek/youbot/src/youbot/brics_actuator/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::brics_actuator::ProgramExecuteVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::brics_actuator::ProgramExecuteVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::brics_actuator::ProgramExecuteVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::brics_actuator::ProgramExecuteVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brics_actuator::ProgramExecuteVelocity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::brics_actuator::ProgramExecuteVelocity_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::brics_actuator::ProgramExecuteVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3dafcaf7789e3ecdfbe8f6970942cec9";
  }

  static const char* value(const ::brics_actuator::ProgramExecuteVelocity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3dafcaf7789e3ecdULL;
  static const uint64_t static_value2 = 0xfbe8f6970942cec9ULL;
};

template<class ContainerAllocator>
struct DataType< ::brics_actuator::ProgramExecuteVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "brics_actuator/ProgramExecuteVelocity";
  }

  static const char* value(const ::brics_actuator::ProgramExecuteVelocity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::brics_actuator::ProgramExecuteVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 velocity\n\
";
  }

  static const char* value(const ::brics_actuator::ProgramExecuteVelocity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::brics_actuator::ProgramExecuteVelocity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ProgramExecuteVelocity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::brics_actuator::ProgramExecuteVelocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::brics_actuator::ProgramExecuteVelocity_<ContainerAllocator>& v)
  {
    s << indent << "velocity: ";
    Printer<int8_t>::stream(s, indent + "  ", v.velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BRICS_ACTUATOR_MESSAGE_PROGRAMEXECUTEVELOCITY_H
